name: Backup PostgreSQL Database

on:
  workflow_call:
    secrets:
      BACKUP_OPENSSL_PASSWORD:
        required: true
      PGPASSWORD:
        required: true
      PGDATABASE:
        required: true
      PGHOST:
        required: true
      PGPORT:
        required: true
      PGUSER:
        required: true

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      POSTGRESQL_VERSION: 16
      PGPASSWORD: ${{ secrets.PGPASSWORD }}

    steps:
      - name: Check Local pg_dump Version
        run: |
          pg_dump --version
          openssl version

      - name: Install PostgreSQL ${{ env.POSTGRESQL_VERSION }}
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install "postgresql-$POSTGRESQL_VERSION"

      - name: Check Installed pg_dump Version
        run: /usr/lib/postgresql/$POSTGRESQL_VERSION/bin/pg_dump --version

      - name: Run pg_dump
        run: /usr/lib/postgresql/$POSTGRESQL_VERSION/bin/pg_dump -U ${{ secrets.PGUSER }} -h ${{ secrets.PGHOST }} -p ${{ secrets.PGPORT }} -F t ${{ secrets.PGDATABASE }} > ./backup

      - name: Encrypt Backup
        run: openssl enc -aes-256-cbc -salt -in ./backup -out ./backup.enc -k ${{ secrets.BACKUP_OPENSSL_PASSWORD }}

      - name: Clean Up
        run: rm -rf ./backup

      - name: Set Artifact Name
        run: echo "ARTIFACT_NAME=backup-$(date -u +%Y-%m-%dT%H%M)" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./backup.enc
          retention-days: 14
