name: Generate Sitemap

on:
  workflow_call:
    secrets:
      GITHUB_USERNAME:
        required: true
      GITHUB_EMAIL:
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  sitemap:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: npm install
      - name: Build and Generate Sitemaps
        run: npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Commit Changes
        run: |
          git config user.name "${{ secrets.GITHUB_USERNAME }}"
          git config user.email "${{ secrets.GITHUB_EMAIL }}"
          git add .
          git commit -m "Update Sitemap"
          git push
